from dataclasses import dataclass
from debussy_concert.data_ingestion.config.movement_parameters.time_partitioned import TimePartitionedDataIngestionMovementParameters


@dataclass(frozen=True)
class BigQueryDataIngestionMovementParameters(TimePartitionedDataIngestionMovementParameters):
    extract_sql_query: str
