name: "sakila_dbt"
version: "1.0.0"
config-version: 2

profile: "bigquery_lakehouse"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

packages-install-path: "{{ env_var('DBT_PACKAGES_INSTALL_PATH') }}"

#target-path: "target"  # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  sakila_dbt:
    sakila:
      +materialized: table
      +persist_docs:
        relation: true
        columns: true
